server:
  port: 18780
  address: 127.0.0.1

spring:
  application:
    name: ERPManager
  datasource:
    url: jdbc:sqlite:./app/data/app.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

inventory:
  app-name: ERPManager 本地端進銷存系統
  version: 0.4.0
  base-dir: ./app
  pdf-dir: ./app/files/pdf
  label-dir: ./app/files/labels
  export-dir: ./app/files/export
  backup-dir: ./app/files/backup
  google-token-dir: ./app/google/tokens
